export const authTypes = {
  AUTH_RESET_LOADING: 'AUTH_RESET_LOAD',
  AUTH_APPLY_LOADING: 'AUTH_APPLY_LOADING',
  AUTH_SETUSER: 'AUTH_REGISTER',
  AUTH_ATT_PROGRESS_LOADING: 'AUTH_ATT_PROGRESS_LOADING',
  ASYNC_AUTH_LOGIN: 'ASYNC_AUTH_LOGIN',
  ASYNC_AUTH_LOGOUT: 'ASYNC_AUTH_LOGOUT',
  ASYNC_AUTH_REGISTER: 'ASYNC_AUTH_REGISTER',
};
